// @codekit-append  "../vendor/jquery/jquery.min.js";
// @codekit-append  "../vendor/bootstrap/bootstrap.bundle.min";
// @codekit-append  "../vendor/datatables/jquery.dataTables.min.js";
// @codekit-append  "../vendor/datatables/dataTables.bootstrap4.min.js";
// @codekit-append  "../vendor/datatables/dataTables.responsive.min.js";
// @codekit-append  "../vendor/datatables/responsive.bootstrap4.min.js";
// @codekit-append  "../vendor/datatables/Spanish.js";
// @codekit-append  "../vendor/sweetalert2/sweetalert2.all.min.js";
// @codekit-append  "./_super-fresco.js";